# Generated by Django 4.0.3 on 2022-04-25 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('quantity', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
