# Generated by Django 4.0.4 on 2022-05-15 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
