# Generated by Django 4.0.4 on 2022-05-15 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_alter_item_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
