# Generated by Django 4.0.3 on 2022-04-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('actual_image', models.ImageField(upload_to='uploads/')),
                ('date_added', models.DateField()),
                ('verified_status', models.BooleanField(default=False)),
                ('stat_hp', models.IntegerField(default=0)),
                ('stat_attack', models.IntegerField(default=0)),
                ('stat_defense', models.IntegerField(default=0)),
                ('stat_speed', models.IntegerField(default=0)),
            ],
        ),
    ]
