# Generated by Django 4.0.3 on 2022-04-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo_Uploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo_data',
            old_name='actual_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='photo_data',
            name='id',
        ),
        migrations.AlterField(
            model_name='photo_data',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
