# Generated by Django 4.0.3 on 2022-04-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo_Uploader', '0002_rename_actual_image_photo_data_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_data',
            name='date_added',
            field=models.DateField(null=True),
        ),
    ]
