# Generated by Django 4.0.3 on 2022-04-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo_Uploader', '0004_photo_data_user_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo_data',
            name='pet_name',
            field=models.CharField(default='', max_length=25),
        ),
    ]
