# Generated by Django 4.0.3 on 2022-04-25 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo_Uploader', '0006_alter_photo_data_pet_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_data',
            name='pet_name',
            field=models.CharField(blank=True, default='Luke', max_length=25),
        ),
    ]
