# Generated by Django 4.0.3 on 2022-05-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo_Uploader', '0007_alter_photo_data_pet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_data',
            name='pet_name',
            field=models.CharField(blank=True, default='Brent', max_length=25),
        ),
    ]
