# Generated by Django 4.0.4 on 2022-05-08 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Photo_Uploader', '0008_photo_data_passes_photo_data_strikes_and_more'),
        ('Photo_Uploader', '0009_alter_photo_data_pet_name'),
    ]

    operations = [
    ]
