# Generated by Django 4.0.3 on 2022-05-10 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo_Uploader', '0010_alter_photo_data_pet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_data',
            name='pet_name',
            field=models.CharField(blank=True, default='Linda', max_length=25),
        ),
        migrations.AlterField(
            model_name='photo_data',
            name='user_id',
            field=models.CharField(max_length=150, primary_key=True, serialize=False),
        ),
    ]
