# Generated by Django 4.0.4 on 2022-05-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photo_Uploader', '0014_alter_photo_data_pet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo_data',
            name='pet_name',
            field=models.CharField(blank=True, default='Marcus', max_length=25),
        ),
    ]
