# Generated by Django 4.0.4 on 2022-05-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_level', models.IntegerField(default=1)),
                ('required_experience', models.IntegerField(default=0)),
                ('required_health', models.IntegerField(default=0)),
                ('challenge_type', models.CharField(default='Battle', max_length=10)),
                ('image', models.CharField(default='', max_length=20)),
                ('completed', models.BooleanField(default=False)),
                ('enemy_hp', models.IntegerField(default=15)),
                ('enemy_att', models.IntegerField(default=2)),
            ],
        ),
    ]
